import Head from 'next/head'
import React,{useState} from 'react'
import Image from 'next/image'
import { useRouter } from 'next/router';
import Promo from '../components/promo.js'
import Footer from '../components/Footer.js'
import Navbar from '../components/Navbar.js'

interface UsersProps {
  dataMenu: Array<any>;
  dataPromo:Array<any>;
}
export default function Home(props: UsersProps) {
  const {dataMenu,dataPromo} = props;
  const router = useRouter();

 const slides=[
    {
      url: 'https://raw.githubusercontent.com/peeweeid/BahanBlueheron/main/image/slider%201.jpg',
    },
    {
        url: 'https://raw.githubusercontent.com/peeweeid/BahanBlueheron/main/image/slider%202.jpg',
    },
    {
        url: 'https://raw.githubusercontent.com/peeweeid/BahanBlueheron/main/image/slider%203.jpg',
    },
    ];
    
    const [currentIndex, setCurrentIndex] = useState(0);

    const prevSlide = () => {
      const isFirstSlide = currentIndex === 0;
      const newIndex = isFirstSlide ? slides.length - 1 : currentIndex - 1;
      setCurrentIndex(newIndex);
    };
    
    const nextSlide = () => {
      const isLastSlide = currentIndex === slides.length - 1;
      const newIndex = isLastSlide ? 0 : currentIndex + 1;
      setCurrentIndex(newIndex);
    };
    
    const goToSlide = (slideIndex:any) => {
      setCurrentIndex(slideIndex);
    };
    
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=''>
      <Navbar />
      </div>
      <section className='bg-secondary overflow-hidden z-30'>
      <div className=''>
     
          <div className=' lg:h-[700px] lg:w-[1320px] h-[210px]  w-[396px] m-auto lg:py-10 py-4 px-4 mb-5 relative group'>
      <div
        style={{ backgroundImage: `url(${slides[currentIndex].url})` }}
        className='w-full h-full bg-center bg-cover duration-200'
      ></div>
      {/* Left Arrow */}
      <div className='hidden group-hover:block absolute top-[50%] -translate-x-0 translate-y-[-50%] left-5 text-2xl rounded-full p-2 bg-black/20 text-white cursor-pointer'>
       
      </div>
      {/* Right Arrow */}
      <div className='hidden group-hover:block absolute top-[50%] -translate-x-0 translate-y-[-50%] right-5 text-2xl rounded-full p-2 bg-black/20 text-white cursor-pointer'>
        
      </div>
      <div className='flex top-4 justify-center py-2'>
        {slides.map((slide, slideIndex) => (
          <div
            key={slideIndex}
            onClick={() => goToSlide(slideIndex)}
            className='text-2xl cursor-pointer'
          >
           o
          </div>
        ))}
      </div>
    </div>
        
      </div>
     </section>
      {/* menu panel */}
      <section className='bg-secondary py-4 overflow-hidden z-30'>
        <h1 className='text-primary text-lg font-bold text-center mb-5'>Menu</h1>
        <div className='container px-4 lg:px-0 lg:max-w-6xl '>
          <div className='flex flex-wrap lg:justify-between justify-center'>
            <div className='flex items-center justify-center lg:w-1/3 w-full'>
                <h1 className='bg-white hover:bg-slate-100 rounded-lg w-20 text-center mr-2 text-sm  text-primary shadow-lg cursor-pointer'>#Drink</h1>
                <h1 className='bg-white hover:bg-slate-100 rounded-lg w-20 text-center mr-2 text-sm text-primary shadow-lg cursor-pointer'>#Food</h1>
                <h1 className='bg-white hover:bg-slate-100 rounded-lg w-20 text-center mr-2 text-sm text-primary shadow-lg cursor-pointer'>#Dessert</h1>
                </div>
             <div className='lg:w-1/3 w-full mt-5 lg:mt-0'>
              <div className='flex justify-center'>
              <input type={'text'} className='h-8 w-56 rounded-bl-lg rounded-tl-lg shadow-lg focus:border-sky-600 focus:outline-none focus:ring-2 focus:ring-sky-500'/>
                <button className='bg-primary h-8 w-8 rounded-br-lg rounded-tr-lg shadow-lg text-white font-bold hover:bg-third'>G</button>
                </div>
             </div>
          </div>
          <div className='flex flex-wrap mt-5'>
              {dataMenu.map((user) => (
                <div key={user.id} id={user.type} className='w-1/2 lg:w-1/4 px-4 mb-2' onClick={()=> router.push (`/Menu/${user.id}`)}>
                  <div className='bg-white hover:bg-slate-100 rounded-xl shadow-xl mx-auto py-4 mb-4 lg:w-64 lg:h-60 cursor-pointer'>
                    <img src={user.Image} alt='' className='mx-auto lg:w-40 lg:h-40 w-20 h-20'/>
                    <h1 className='text-center text-lg font-bold'>{user.nama}</h1>
                    <h1 className='text-center text-base'>{user.harga}</h1>
                   
                  </div>
                </div>
            ))}
          </div>
         
          <div className='flex items-center justify-center lg:mb-5 mb-16'>
          <button className='px-4 py-2 w-52 bg-primary hover:bg-third rounded-lg text-white font-bold'>Load More</button>  
          </div>
         
        </div>
      </section>
      <div className='relative'>
      <Footer />
      </div>
    </>
  )  
}
export async function getStaticProps() {
  const res = await fetch ('https://json-blueheron.vercel.app/menu')
  const dataMenu = await res.json()
  const rus = await fetch ('https://json-blueheron.vercel.app/promo/')
  const dataPromo = await rus.json()
  return {
      props :{
          dataMenu,
          dataPromo
      }
  }
}
